"""empty message

Revision ID: d59f7ae13ead
Revises: 
Create Date: 2025-09-04 18:45:21.172652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59f7ae13ead'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('members_rights', sa.Boolean(), nullable=False),
    sa.Column('welcome_message', sa.String(length=4100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_interaction', sa.Boolean(), nullable=False),
    sa.Column('command', sa.String(length=4096), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'command', name='unique_command_for_chat'),
    sa.UniqueConstraint('id')
    )
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=4096), nullable=False),
    sa.Column('answer', sa.String(length=4096), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'word', name='unique_word_for_chat'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triggers')
    op.drop_table('actions')
    op.drop_table('chats')
    # ### end Alembic commands ###
